### ISSUE TITLE
rpc proxy

### ISSUE THREAD

**Issue by dmi-feo** [dmi-feo/ytsaurus-local#10]

**Comment by dmi-feo** [comment]
```
# curl http://localhost/api/v4/discover_proxies
{"proxies":[]}
```

**Comment by dmi-feo** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/yt/wrapper/cypress_commands.py", line 352, in list
    result = make_formatted_request(
  File "/usr/local/lib/python3.10/dist-packages/yt/wrapper/driver.py", line 179, in make_formatted_request
    result = make_request(command_name, params,
  File "/usr/local/lib/python3.10/dist-packages/yt/wrapper/driver.py", line 107, in make_request
    result = native_driver.make_request(
  File "/usr/local/lib/python3.10/dist-packages/yt/wrapper/native_driver.py", line 344, in make_request
    raise error
yt.wrapper.errors.YtRpcUnavailable: Received driver response with error
    No alive peers found
        Discovery request failed for peer localhost:20069
            Service is not registered

***** Details:
Received driver response with error
    origin          8b0f448a91a5 on 2024-08-28T10:28:49.510643Z
No alive peers found
    code            105
    origin          (unknown) on 2024-08-28T10:28:49.501058Z (pid 2781, tid 2067683360e9b0ae, fid fffeef408a65b90a)
    connection_id   92c64059-d7119a4f-844bedec-63b1ad
    thread          RpcLight
    channel_failure_error_handled true
    rpc_proxy       true
    cluster_url     http://localhost
    service         ApiService
Discovery request failed for peer localhost:20069
    origin          (unknown) on 2024-08-28T10:28:49.500299Z (pid 2781, tid 2067683360e9b0ae, fid fffeef408a65b90a)
    connection_id   92c64059-d7119a4f-844bedec-63b1ad
    thread          RpcLight
    rpc_proxy       true
    cluster_url     http://localhost
    service         ApiService
Service is not registered
    code            102
    origin          localhost on 2024-08-28T10:28:49.496793Z (pid 14, tid f23d7c2e99154b09, fid fffeef3ac0ee7ce7)
    request_id      2087d8a4-17c0fe85-bfed3679-bb4fe957
    connection_id   37fe7137-9c7435e6-3808b73e-1806b8ba
    verification_mode none
    realm_id        0-0-0-0
    thread          BusXferFS:1
    channel_failure_error_handled true
    timeout         15000
    method          Discover
    address         localhost:20069
    encryption_mode optional
    service         ApiService
```

**Comment by dmi-feo** [comment]
role=default for proxy?
